In [1]:
import tqdm.notebook as tqdm

In [2]:
with open('input.txt', 'r') as in_file:
    raw_data = in_file.readlines()
N = int(raw_data[0].strip())
tasks_difficult = [int(el) for el in raw_data[1].strip().split()]
tasks_time = [float(el.strip()) for el in raw_data[2].strip().split()]
M = int(raw_data[3].strip())
tasks_diff_coef = [[ float(el) for el in line.strip().split()] for line in raw_data[4:]]

In [26]:
ga.individual_diff_coef

array([[0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       [0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       [0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       ...,
       [1.  , 1.52, 0.61, ..., 1.52, 1.02, 0.37],
       [0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       [1.23, 1.5 , 0.44, ..., 1.52, 1.02, 0.66]])

In [27]:
ga.np_tasks_diff_coef

array([[0.54, 1.17, 1.52, 2.18],
       [0.31, 0.66, 1.13, 1.76],
       [0.48, 1.09, 1.78, 2.39],
       [0.61, 1.09, 1.5 , 2.04],
       [0.66, 1.02, 1.42, 1.79],
       [0.44, 0.77, 1.16, 1.47],
       [0.59, 1.23, 1.59, 2.13],
       [0.49, 1.08, 1.67, 2.35],
       [0.55, 1.  , 1.3 , 1.67],
       [0.37, 0.8 , 1.44, 2.01]])

In [29]:
ga.np_tasks_diff_coef[ga.population, ga.np_tasks_diff]

array([[0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       [0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       [0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       ...,
       [1.  , 1.52, 0.61, ..., 1.52, 1.02, 0.37],
       [0.66, 1.3 , 0.44, ..., 1.52, 1.02, 0.54],
       [1.23, 1.5 , 0.44, ..., 1.52, 1.02, 0.66]])

In [30]:
ga.population

array([[1, 8, 5, ..., 0, 4, 0],
       [1, 8, 5, ..., 0, 4, 0],
       [1, 8, 5, ..., 0, 4, 0],
       ...,
       [8, 0, 3, ..., 0, 4, 9],
       [1, 8, 5, ..., 0, 4, 0],
       [6, 3, 5, ..., 0, 4, 4]], dtype=int64)

In [31]:
ga.np_tasks_diff

array([1, 2, 0, 1, 3, 3, 1, 1, 1, 3, 2, 2, 3, 3, 0, 2, 1, 3, 3, 0, 2, 0,
       1, 1, 2, 1, 2, 1, 3, 3, 3, 2, 1, 2, 3, 3, 2, 0, 2, 3, 0, 0, 1, 1,
       2, 1, 0, 2, 3, 2, 1, 1, 3, 1, 1, 0, 1, 2, 1, 2, 1, 3, 2, 1, 2, 0,
       2, 1, 0, 3, 1, 3, 3, 3, 2, 1, 1, 0, 3, 0, 1, 3, 1, 0, 3, 0, 1, 1,
       3, 2, 1, 2, 2, 0, 0, 2, 1, 0, 3, 3, 3, 3, 0, 1, 1, 0, 3, 0, 2, 1,
       2, 0, 3, 3, 2, 2, 0, 0, 3, 0, 3, 0, 0, 1, 1, 3, 0, 2, 2, 2, 2, 3,
       0, 3, 1, 3, 1, 0, 0, 1, 0, 2, 1, 3, 2, 3, 1, 3, 2, 0, 2, 3, 1, 3,
       2, 1, 2, 1, 2, 3, 0, 3, 2, 3, 1, 1, 2, 2, 3, 3, 1, 3, 1, 3, 1, 2,
       0, 3, 0, 0, 1, 3, 1, 1, 3, 3, 2, 2, 3, 1, 1, 1, 0, 3, 2, 0, 2, 2,
       3, 2, 1, 0, 3, 2, 2, 0, 3, 2, 2, 3, 0, 2, 3, 1, 0, 2, 0, 1, 2, 1,
       1, 1, 2, 3, 0, 1, 0, 0, 3, 0, 1, 1, 3, 1, 3, 3, 3, 0, 3, 2, 0, 2,
       0, 3, 0, 2, 0, 3, 1, 0, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 1,
       3, 0, 2, 3, 3, 0, 2, 1, 0, 1, 3, 3, 0, 0, 2, 3, 2, 3, 1, 3, 3, 1,
       0, 1, 0, 1, 2, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2,

In [22]:
import numpy as np

class GeneticAlgorithm:

    def __init__(
      self,
      N: int,
      tasks_difficult: list[int],
      tasks_time: list[float],
      M: int,
      tasks_diff_coef: list[list[float]],
      size_population: int
  ):
        self.N = N #количество задач
        self.M = M #количество работников
        self.tasks_difficult = tasks_difficult #список сложностей задач
        self.tasks_time = tasks_time #время на решение задачи
        self.tasks_diff_coef = tasks_diff_coef #2D список коэффициентов решения задач (строка - номер рабоника, столбец задача, элемент - коэффициент)
        self.size_population = size_population

        self.rng = np.random.default_rng()
        self.population = self.rng.integers(self.M, size=(size_population, self.N)) #тут создается популяция индив. строки - особи, столбцы - номер задачи

    def fitness(self):

        self.np_tasks_diff = np.array(self.tasks_difficult)-1
        self.np_tasks_diff_coef = np.array(self.tasks_diff_coef)
        self.individual_diff_coef = self.np_tasks_diff_coef[self.population, self.np_tasks_diff]
        res = self.individual_diff_coef * self.tasks_time

        #не робит
        result = []
        for worker in range(self.M):
            result.append(res.sum(axis=1, where=self.population==worker))
        #score = res.sum(axis=1)
        return np.array(result).max(axis=0)
    
    #range selection
    def selection(self, percent):
        idx = np.argsort(self.fitness())[:round(self.size_population*percent)]
        self.selected_individuums = self.population[idx]

    def uniform_crossover(self):
        selected_size = self.selected_individuums.shape[0]
        n_childrens = self.size_population - selected_size
        mask = self.rng.choice([True, False], size=self.selected_individuums.shape[-1])

        father = self.rng.integers(low=0, high=selected_size, size=selected_size)
        shift = self.rng.integers(selected_size)
        mother = (father + shift) % selected_size
        self.new_generation = np.where(mask, self.selected_individuums[father], self.selected_individuums[mother])

    def mutation(self) -> None:
        self.p_mutation_ind = 0.8
        self.p_mutation_gen = 0.5
        mask = self.rng.random(size=self.new_generation.shape[0]) <= self.p_mutation_ind
        mutating_children = self.new_generation[mask]
        mutating_children[...] = np.where(
            self.rng.random(size=mutating_children.shape) <= self.p_mutation_gen,
            self.rng.integers(low=0, high=self.M, size=mutating_children.shape),
            mutating_children
        )
        self.new_generation[mask] = mutating_children

    def step(self):
        self.selection(0.5)
        self.uniform_crossover()
        self.mutation()
        self.population = np.concatenate([self.selected_individuums, self.new_generation], axis=0)


ga = GeneticAlgorithm(N, tasks_difficult, tasks_time, M, tasks_diff_coef, 200)

In [23]:
progress_bar = tqdm.trange(6000)
for i in progress_bar:
    ga.step()
100/ga.fitness().min()

  0%|          | 0/6000 [00:00<?, ?it/s]

0.1647799363949446

In [24]:
100/ga.fitness().min()

0.1647799363949446

In [25]:
print(*ga.population[np.argmin(ga.fitness())]+1)

2 9 6 10 7 8 3 4 3 4 9 10 7 10 10 10 3 6 6 8 7 7 6 1 7 10 3 7 9 8 7 4 6 2 10 7 9 6 8 2 2 8 10 9 8 1 2 6 5 2 10 5 6 10 3 8 7 8 5 5 10 8 5 1 10 4 4 3 8 6 10 6 7 6 1 9 4 8 9 10 7 8 8 6 9 1 10 8 9 3 4 5 8 6 9 2 6 4 2 1 3 6 4 10 9 1 8 3 5 7 5 3 4 9 7 10 10 1 5 10 6 3 3 9 6 4 3 9 4 7 9 9 6 7 8 8 5 1 7 1 2 1 4 5 2 4 6 10 3 7 2 8 6 4 6 9 7 4 9 2 1 2 9 5 10 7 6 1 6 3 10 6 2 9 6 7 7 9 2 7 3 4 3 3 2 6 10 4 2 6 5 9 3 4 8 7 1 3 5 2 2 7 6 2 2 10 4 1 2 7 1 9 2 3 1 5 1 6 10 7 10 9 9 1 6 3 7 1 7 8 3 2 7 4 9 1 7 1 8 9 7 6 7 6 10 5 4 10 1 8 6 6 8 7 9 3 7 2 3 1 4 2 10 4 5 10 10 5 2 10 8 10 2 10 5 9 5 1 7 6 7 8 4 3 6 6 1 8 2 8 4 4 3 9 5 2 2 2 4 6 1 3 6 6 8 3 9 5 6 3 2 10 5 6 8 1 3 5 4 1 6 9 6 10 6 9 7 6 5 1 2 2 10 9 3 6 8 5 7 8 8 5 4 2 2 2 3 7 4 7 3 10 10 6 10 1 5 2 1 5 7 7 8 9 6 10 1 2 1 4 5 5 6 9 10 4 1 10 9 6 2 5 7 5 7 4 7 9 4 8 5 7 10 7 8 6 6 6 1 10 6 4 10 1 8 1 10 2 4 4 9 5 4 2 9 8 2 4 10 5 2 7 10 2 1 7 7 10 10 10 4 1 1 10 10 7 2 10 2 10 10 7 1 4 8 9 8 10 2 9 4 5 8 4 10 6 9 6 8 7 6 8 9 2 9 5 8 8 9 10 